// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKB9-5t6dHgliaSchnF7z9rfRI62HtijY',
    appId: '1:1078366095798:web:628dd18fc4715b45165917',
    messagingSenderId: '1078366095798',
    projectId: 'reddit-clone-s0708',
    authDomain: 'reddit-clone-s0708.firebaseapp.com',
    storageBucket: 'reddit-clone-s0708.appspot.com',
    measurementId: 'G-CRL99PS5YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCjgVaRoUY6xL580QugK6SBtoFnFPVNrs',
    appId: '1:1078366095798:android:676cd62aa531222a165917',
    messagingSenderId: '1078366095798',
    projectId: 'reddit-clone-s0708',
    storageBucket: 'reddit-clone-s0708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC11SMiSvMJWgweCuk7Ou0bG-234hhrxOg',
    appId: '1:1078366095798:ios:d75cf9568e137880165917',
    messagingSenderId: '1078366095798',
    projectId: 'reddit-clone-s0708',
    storageBucket: 'reddit-clone-s0708.appspot.com',
    iosClientId: '1078366095798-i4ggugspc9h9qlcp5odek59n50b5lpdj.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC11SMiSvMJWgweCuk7Ou0bG-234hhrxOg',
    appId: '1:1078366095798:ios:4b3ae0ac80aee92f165917',
    messagingSenderId: '1078366095798',
    projectId: 'reddit-clone-s0708',
    storageBucket: 'reddit-clone-s0708.appspot.com',
    iosClientId: '1078366095798-rr395bdbfmsrkomg0p1s0nvh1foltso0.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit.RunnerTests',
  );
}
